fastapi:
  replicaCount: 1
  image:
    repository: dyegodev30/k8s  
    pullPolicy: IfNotPresent  
    tag: "v1.0.2"  

  service:   
    type: ClusterIP    
    port: 6000
  
  # This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ingress:
    enabled: true
    className: "nginx"
    annotations: 
      kubernetes.io/ingress.class: nginx    
    hosts:
       - host: api.dyego.lab
         paths:
           - path: /
             pathType: Prefix
    tls: []
  
    
  resources:   
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi 
 
  
  autoscaling:
     enabled: false
     minReplicas: 1
     maxReplicas: 100
     targetCPUUtilizationPercentage: 80

  securityContext:
   runAsUser: 0
  