default:
  replicaCount: 1
  image:
    repository: dyegodev30/k8s  
    pullPolicy: IfNotPresent  
    tag: v1.0.4  

  service:   
    type: ClusterIP    
    port: 6000
  
  ingress:
    enabled: true
    className: "nginx"
    annotations: 
      kubernetes.io/ingress.class: nginx    
    hosts:
       - host: api.dyego.lab
         paths:
           - path: /
             pathType: Prefix
    tls: []

  resources:   
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi 

  autoscaling:
     enabled: false
     minReplicas: 1
     maxReplicas: 100
     targetCPUUtilizationPercentage: 80

  securityContext:
   runAsUser: 0

  storageClass:
    create: false
    name: local-storage

  persistence:
    enabled: false
    size: 1Gi
    storageClass: local-storage

  persistentVolume:
    create: false
    path: /mnt/data/grafana  # Caminho no nó
    node: worker1
